#This is a template config for custom finetuning kronos on csv data
#这是一份模板config，用于kronos的csv自定义数据微调

data:
  data_path: "/gemini/code/finetune_csv/data/hstech.csv"
  lookback_window: 250
  predict_window: 5
  max_context: 512
  clip: 5.0
  train_ratio: 0.85
  val_ratio: 0.15
  test_ratio: 0.0

training:
  tokenizer_epochs: 0
  basemodel_epochs: 6
  batch_size: 32
  
  log_interval: 10
  num_workers: 6
  seed: 100

  n_train_iter: 1280
  n_val_iter: 256
  
  tokenizer_learning_rate: 0.0
  predictor_learning_rate: 0.000008
  
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_weight_decay: 0.3
  
  accumulation_steps: 1

# model path configuration
model_paths:
  # pretrained model path
  pretrained_tokenizer: "/gemini/data-1/Kronos-Tokenizer-base"
  pretrained_predictor: "/gemini/data-1/Kronos-base"
  
  # experiment name - other paths will be generated based on this
  exp_name: "hstech"
  base_path: "/gemini/code/finetune_csv/finetuned/"

  # the following paths will be generated based on exp_name, no need to modify manually
  # way 1: leave empty string, the system will generate the full path
  # base_save_path: ""  #  /xxxx/Kronos/finetune_csv/finetuned/{exp_name}
  # finetuned_tokenizer: ""  # /xxxx/Kronos/finetune_csv/finetuned/{exp_name}/tokenizer/best_model
  
  # way 2: use template string, {exp_name} will be replaced with the actual experiment name
  base_save_path: "/gemini/data-1/finetune_csv/finetuned/{exp_name}"
  finetuned_tokenizer: "/gemini/data-1/Kronos-Tokenizer-base"
  
  tokenizer_save_name: "tokenizer"
  basemodel_save_name: "basemodel"

experiment:
  name: "hstech"
  description: ""
  use_comet: false
  
  # control the training phase
  train_tokenizer: false
  train_basemodel: true
  
  # if true, skip the existing model training
  skip_existing: false

# device configuration
device:
  use_cuda: true
  device_id: 0
  
